apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-config
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: delinea-secretstore
    kind: SecretStore
  target:
    name: airflow-env
  data:
    - secretKey: AIRFLOW__CORE__FERNET_KEY
      remoteRef:
        key: path/to/fernet
    - secretKey: AIRFLOW_CONN_MSSQL
      remoteRef:
        key: path/to/mssql/conn
