apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: delinea-secretstore
spec:
  provider:
    delinea:
      serverUrl: https://your-secret-server
      auth:
        accessTokenSecretRef:
          name: delinea-token
          key: token
