#!/bin/bash
# Port Discovery Script for Parallel Development
#
# This script discovers the actual ports assigned to services,
# supporting parallel Astronomer development workflows.

set -e

PROJECT_NAME="{{cookiecutter.project_slug}}"
DEPLOYMENT_MODE="{{cookiecutter.deployment_mode}}"
if [[ "$DEPLOYMENT_MODE" == "testing" ]]; then
    PROJECT_NAME="${PROJECT_NAME}-test"
fi

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔍 Discovering service ports for: ${PROJECT_NAME}${NC}"
echo

# Function to get container port mapping
get_container_port() {
    local container_name="$1"
    local internal_port="$2"

    if ! docker ps --format "table {%raw%}{{.Names}}\t{{.Status}}{%endraw%}" | grep -q "$container_name"; then
        echo -e "${RED}❌ Container '$container_name' not running${NC}"
        return 1
    fi

    local port_mapping=$(docker port "$container_name" "$internal_port" 2>/dev/null | head -1)
    if [[ -z "$port_mapping" ]]; then
        echo -e "${YELLOW}⚠️  No port mapping found for $container_name:$internal_port${NC}"
        return 1
    fi

    echo "$port_mapping" | cut -d':' -f2
}

# Function to check service health
check_service_health() {
    local service_name="$1"
    local url="$2"

    if curl -s -o /dev/null -w "%{http_code}" "$url" | grep -q "200\|302\|401"; then
        echo -e "${GREEN}✅ $service_name is healthy${NC}"
        return 0
    else
        echo -e "${YELLOW}⚠️  $service_name may not be ready yet${NC}"
        return 1
    fi
}

echo -e "${BLUE}📡 Service Discovery:${NC}"

# Discover Airflow Webserver
AIRFLOW_CONTAINER="${PROJECT_NAME}-airflow-webserver"
if AIRFLOW_PORT=$(get_container_port "$AIRFLOW_CONTAINER" "8080"); then
    AIRFLOW_URL="http://localhost:$AIRFLOW_PORT"
    echo -e "  🌐 ${GREEN}Airflow UI:${NC} $AIRFLOW_URL"
    check_service_health "Airflow" "$AIRFLOW_URL" || true
else
    echo -e "  🌐 ${RED}Airflow UI: Not available${NC}"
fi

# Discover PostgreSQL
POSTGRES_CONTAINER="${PROJECT_NAME}-postgres"
if POSTGRES_PORT=$(get_container_port "$POSTGRES_CONTAINER" "5432"); then
    echo -e "  🗄️  ${GREEN}PostgreSQL:${NC} localhost:$POSTGRES_PORT"
    echo -e "     ${BLUE}Connection string:${NC} postgresql://admin:admin@localhost:$POSTGRES_PORT/{{cookiecutter.db_name}}"
else
    echo -e "  🗄️  ${RED}PostgreSQL: Not available${NC}"
fi

echo

# Export as environment variables for scripts
if [[ -n "$AIRFLOW_PORT" ]]; then
    export DISCOVERED_AIRFLOW_PORT="$AIRFLOW_PORT"
    export AIRFLOW_URL="http://localhost:$AIRFLOW_PORT"
fi

if [[ -n "$POSTGRES_PORT" ]]; then
    export DISCOVERED_POSTGRES_PORT="$POSTGRES_PORT"
    export DATABASE_URL="postgresql://admin:admin@localhost:$POSTGRES_PORT/{{cookiecutter.db_name}}"
fi

# Create environment file for other scripts
cat > .env.ports << EOF
# Auto-discovered service ports
# Generated by scripts/get-ports.sh
DISCOVERED_AIRFLOW_PORT=${AIRFLOW_PORT:-}
DISCOVERED_POSTGRES_PORT=${POSTGRES_PORT:-}
AIRFLOW_URL=${AIRFLOW_URL:-}
DATABASE_URL=${DATABASE_URL:-}
PROJECT_NAME=${PROJECT_NAME}
EOF

echo -e "${GREEN}✅ Port discovery complete${NC}"
echo -e "${BLUE}💡 Port information saved to .env.ports${NC}"

# Check for conflicts with other projects
echo
echo -e "${BLUE}🔍 Checking for port conflicts:${NC}"

# Find other running Astronomer projects
OTHER_PROJECTS=$(docker ps --filter "label=de-template.service=airflow-webserver" --format "{%raw%}{{.Names}}{%endraw%}" | grep -v "$AIRFLOW_CONTAINER" || true)

if [[ -n "$OTHER_PROJECTS" ]]; then
    echo -e "${YELLOW}⚠️  Other Astronomer projects running:${NC}"
    for project in $OTHER_PROJECTS; do
        if other_port=$(get_container_port "$project" "8080" 2>/dev/null); then
            echo -e "  📦 $project → http://localhost:$other_port"
        fi
    done
    echo -e "${BLUE}💡 Multiple projects supported - use different browser tabs/windows${NC}"
else
    echo -e "${GREEN}✅ No port conflicts detected${NC}"
fi

# Show quick access commands
if [[ -n "$AIRFLOW_URL" ]]; then
    echo
    echo -e "${BLUE}🚀 Quick Access:${NC}"
    echo -e "  ${GREEN}Open Airflow UI:${NC} $AIRFLOW_URL"
    if command -v open >/dev/null 2>&1; then
        echo -e "  ${BLUE}Command:${NC} open $AIRFLOW_URL"
    elif command -v xdg-open >/dev/null 2>&1; then
        echo -e "  ${BLUE}Command:${NC} xdg-open $AIRFLOW_URL"
    fi
fi