#!/bin/bash
# Development environment setup for Astronomer-based project
# Generated by data-eng-template

set -euo pipefail

echo "🚀 Setting up Astronomer development environment..."
echo
echo "💡 TIP: For the best developer experience, use VS Code DevContainer instead:"
echo "   code . → Click 'Reopen in Container' → Everything starts automatically!"
echo
echo "   This script is for manual setup when DevContainer isn't available."
echo

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check prerequisites
echo "🔍 Checking prerequisites..."

# Check Docker
if ! command_exists docker; then
    echo "❌ Docker not found. Please install Docker Desktop first."
    echo "   Visit: https://docs.docker.com/get-docker/"
    exit 1
fi

# Check Docker Compose
if ! docker compose version >/dev/null 2>&1; then
    echo "❌ Docker Compose not found. Please install Docker Compose."
    exit 1
fi

echo "✅ Docker and Docker Compose found"

# Check Astro CLI (optional but recommended)
if command_exists astro; then
    echo "✅ Astro CLI found ($(astro version))"
    ASTRO_AVAILABLE=true
else
    echo "⚠️  Astro CLI not found - install for optimal experience:"
    echo "   curl -sSL https://install.astronomer.io | bash"
    ASTRO_AVAILABLE=false
fi

# Check uv (for dependency management)
if command_exists uv; then
    echo "✅ uv found ($(uv --version))"
    UV_AVAILABLE=true
else
    echo "⚠️  uv not found - install for dependency management:"
    echo "   curl -LsSf https://astral.sh/uv/install.sh | sh"
    UV_AVAILABLE=false
fi

echo

# Setup environment file
echo "⚙️  Setting up environment configuration..."
if [ ! -f .env ]; then
    if [ -f .env.example ]; then
        cp .env.example .env
        echo "✅ Created .env from .env.example"
    else
        echo "⚠️  No .env.example found - creating minimal .env"
        cat > .env << EOF
# Astronomer Development Environment
COMPOSE_PROJECT_NAME={{cookiecutter.customer_slug}}-etl
AIRFLOW_EXECUTOR={{cookiecutter.executor}}
POSTGRES_VERSION={{cookiecutter.postgres_version}}
PYTHON_VERSION={{cookiecutter.python_version}}
EOF
    fi
else
    echo "✅ .env file already exists"
fi

# Install dependencies if uv is available
if [ "$UV_AVAILABLE" = true ]; then
    echo "📦 Installing dependencies..."
    uv sync
    echo "✅ Dependencies installed"
    
    # Export requirements if needed
    if [ ! -f requirements.txt ] || [ pyproject.toml -nt requirements.txt ]; then
        echo "📋 Exporting requirements.txt..."
        uv export --frozen --no-hashes -o requirements.txt
        echo "✅ requirements.txt updated"
    fi
else
    echo "⚠️  Skipping dependency installation (uv not available)"
fi

# Initialize with Astro CLI if available
if [ "$ASTRO_AVAILABLE" = true ]; then
    echo "🎯 Using Astro CLI for development..."
    
    # Initialize if not already done
    if [ ! -f airflow_settings.yaml ]; then
        echo "🔧 Initializing Astro project..."
        astro dev init --no-overwrite
        echo "✅ Astro project initialized"
    fi
    
    echo "🚀 Starting Astro development environment..."
    astro dev start
    echo "✅ Astro development environment started"
    
    echo
    echo "🎉 Development environment ready!"
    echo "🌐 Access Airflow UI: http://localhost:8080"
    echo "📊 Check service status: astro dev ps"
    echo "📝 View logs: astro dev logs"
    
else
    echo "🔧 Using Docker Compose for development..."
    
    # Start services with Docker Compose
    if [ -f .devcontainer/compose.yaml ]; then
        echo "🚀 Starting services..."
        cd .devcontainer
        docker compose up -d
        cd ..
        echo "✅ Services started"
        
        echo
        echo "🎉 Development environment ready!"
        echo "🌐 Access services via configured ports"
        echo "📊 Check service status: docker compose -f .devcontainer/compose.yaml ps"
        
    else
        echo "❌ No compose.yaml found in .devcontainer/"
        exit 1
    fi
fi

# Show helpful next steps
echo
echo "📚 Next steps:"
echo "   • Check running services: ./tools/where.sh"
echo "   • View project documentation: cat CLAUDE.md"
echo "   • Configure secrets: see secrets/CLAUDE.md"
{% if cookiecutter.enable_kerberos == "yes" %}
echo "   • Configure Kerberos: see kerberos/CLAUDE.md"
{% endif %}
echo "   • Deploy to environments: see envs/CLAUDE.md"

echo
echo "🎯 Happy developing with Astronomer!"