#!/bin/bash
# Quick validation script to check if DCM is completely removed
# Generated by data-eng-template

set -euo pipefail

echo "🔍 DCM Cleanup Validation"
echo "========================"
echo

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

validation_passed=true
issues=()

echo "📋 Checking DCM command availability..."
for cmd in dcm dcm-setup dcm-cache; do
    if command_exists "$cmd"; then
        echo "   ❌ $cmd is still available"
        issues+=("Command $cmd still available")
        validation_passed=false
    else
        echo "   ✅ $cmd successfully removed"
    fi
done

echo
echo "📋 Checking Docker resources..."

# Check DCM containers
dcm_containers=$(docker ps -aq --filter "label=devcontainer-service-manager" 2>/dev/null | wc -l)
if [ "$dcm_containers" -eq 0 ]; then
    echo "   ✅ No DCM containers found"
else
    echo "   ❌ $dcm_containers DCM containers still present:"
    docker ps -a --filter "label=devcontainer-service-manager" --format "     {{.Names}} ({{.Status}})"
    issues+=("$dcm_containers DCM containers remain")
    validation_passed=false
fi

# Check DCM images
dcm_images=$(docker images -q --filter "label=devcontainer-service-manager" 2>/dev/null | wc -l)
if [ "$dcm_images" -eq 0 ]; then
    echo "   ✅ No DCM images found"
else
    echo "   ❌ $dcm_images DCM images still present:"
    docker images --filter "label=devcontainer-service-manager" --format "     {{.Repository}}:{{.Tag}}"
    issues+=("$dcm_images DCM images remain")
    validation_passed=false
fi

# Check cache registry
cache_containers=$(docker ps -aq --filter "name=dcm-cache-registry" 2>/dev/null | wc -l)
if [ "$cache_containers" -eq 0 ]; then
    echo "   ✅ No cache registry containers found"
else
    echo "   ❌ $cache_containers cache registry containers still present"
    docker ps -a --filter "name=dcm-cache-registry" --format "     {{.Names}} ({{.Status}})"
    issues+=("$cache_containers cache registry containers remain")
    validation_passed=false
fi

# Check DCM volumes
dcm_volumes=$(docker volume ls -q --filter "label=devcontainer-service-manager" 2>/dev/null | wc -l)
if [ "$dcm_volumes" -eq 0 ]; then
    echo "   ✅ No DCM volumes found"
else
    echo "   ❌ $dcm_volumes DCM volumes still present"
    docker volume ls --filter "label=devcontainer-service-manager" --format "     {{.Name}}"
    issues+=("$dcm_volumes DCM volumes remain")
    validation_passed=false
fi

echo
echo "📋 Checking configuration directories..."
config_dirs=(
    "$HOME/.config/devcontainer-service-manager"
    "$HOME/.devcontainer-service-manager" 
    "$HOME/.dcm"
    "$HOME/.cache/devcontainer-service-manager"
)

config_issues=0
for config_dir in "${config_dirs[@]}"; do
    if [ -d "$config_dir" ]; then
        echo "   ❌ Config directory still exists: $config_dir"
        issues+=("Config directory remains: $config_dir")
        validation_passed=false
        config_issues=$((config_issues + 1))
    fi
done

if [ $config_issues -eq 0 ]; then
    echo "   ✅ No DCM config directories found"
fi

echo
echo "========================"
if [ "$validation_passed" = true ]; then
    echo "🎉 Validation PASSED"
    echo "✅ DCM appears to be completely removed"
    echo "✅ System is ready for fresh installation"
else
    echo "❌ Validation FAILED"
    echo "Issues found:"
    for issue in "${issues[@]}"; do
        echo "   • $issue"
    done
    echo
    echo "💡 Suggested actions:"
    echo "   • Run: ./scripts/uninstall-dcm.sh"
    echo "   • Or manually clean up remaining resources"
    echo "   • Try: docker system prune -a --volumes"
fi

echo
echo "📊 Summary:"
echo "   DCM containers: $dcm_containers"
echo "   DCM images: $dcm_images" 
echo "   Cache containers: $cache_containers"
echo "   DCM volumes: $dcm_volumes"
echo "   Config directories: $config_issues"