# Modern Docker Compose setup using custom Airflow image
name: {{cookiecutter.repo_slug}}-modern

x-airflow-env: &airflow-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/{{cookiecutter.db_name}}
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__FERNET_KEY: "Jdt_v-EBOLGPgFutJ2oTnin0bIaZPM3SkM0vAOuj9uU="
  _AIRFLOW_WWW_USER_USERNAME: "admin"
  _AIRFLOW_WWW_USER_PASSWORD: "admin"

x-airflow-volumes: &airflow-volumes
  - ../dags:/opt/airflow/dags:cached
  - ../transforms:/opt/airflow/transforms:cached
  - ../scripts:/opt/airflow/scripts:cached
  - ../conf:/opt/airflow/conf:cached
  - airflow_logs:/opt/airflow/logs

services:
  postgres:
    image: postgres:{{cookiecutter.postgres_version}}
    environment:
      POSTGRES_DB: "{{cookiecutter.db_name}}"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    build:
      context: ..
      dockerfile: Dockerfile.airflow
      target: development
    image: {{cookiecutter.repo_slug}}-airflow-dev
    environment: *airflow-env
    user: "50000:0"
    volumes: *airflow-volumes
    command: [
      "bash", "-c",
      "airflow db upgrade && airflow users create --username $$_AIRFLOW_WWW_USER_USERNAME --password $$_AIRFLOW_WWW_USER_PASSWORD --firstname Admin --lastname User --role Admin --email admin@example.com || true"
    ]
    depends_on:
      postgres:
        condition: service_healthy

  airflow-scheduler:
    build:
      context: ..
      dockerfile: Dockerfile.airflow
      target: development
    image: {{cookiecutter.repo_slug}}-airflow-dev
    environment: *airflow-env
    user: "50000:0"
    command: ["airflow", "scheduler"]
    volumes: *airflow-volumes
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-webserver:
    build:
      context: ..
      dockerfile: Dockerfile.airflow
      target: development
    image: {{cookiecutter.repo_slug}}-airflow-dev
    environment: *airflow-env
    user: "50000:0"
    command: ["airflow", "webserver"]
    ports:
      - "8081:8080"
    volumes: *airflow-volumes
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  # DevContainer service (what VS Code opens into)
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:{{cookiecutter.python_version}}
    command: sleep infinity
    user: "1000:1000"
    init: true
    volumes:
      - ..:/workspaces/{{cookiecutter.repo_slug}}
    working_dir: /workspaces/{{cookiecutter.repo_slug}}
    depends_on:
      - airflow-webserver
      - airflow-scheduler
      - postgres

volumes:
  pg_data:
  airflow_logs: