# DevContainer Services Configuration for {{cookiecutter.project_name}}
# Managed by DevContainer Service Manager (dcm)

namespace: "{{cookiecutter.repo_slug}}"
port_range: "auto"

services:
  postgres:
    template: "postgres:{{cookiecutter.postgres_version}}"
    persistent: true
    health_check: true
    environment:
      POSTGRES_DB: "{{cookiecutter.db_name}}"
      POSTGRES_USER: "{{cookiecutter.db_user}}"
      POSTGRES_PASSWORD: "{{cookiecutter.db_password}}"
  
  airflow-init:
    template: "airflow:{{cookiecutter.airflow_version}}"
    component: "init"
    depends_on: ["postgres"]
    persistent: false
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://{{cookiecutter.db_user}}:{{cookiecutter.db_password}}@{{cookiecutter.repo_slug}}_postgres:5432/{{cookiecutter.db_name}}"
      AIRFLOW__CORE__FERNET_KEY: "PLACEHOLDER_AIRFLOW_FERNET_KEY"
      _AIRFLOW_WWW_USER_USERNAME: "PLACEHOLDER_AIRFLOW_WEB_USER"
      _AIRFLOW_WWW_USER_PASSWORD: "PLACEHOLDER_AIRFLOW_WEB_PASSWORD"

  airflow-scheduler:
    template: "airflow:{{cookiecutter.airflow_version}}"
    component: "scheduler"
    depends_on: ["airflow-init"]
    persistent: true
    health_check: true
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://{{cookiecutter.db_user}}:{{cookiecutter.db_password}}@{{cookiecutter.repo_slug}}_postgres:5432/{{cookiecutter.db_name}}"
      AIRFLOW__CORE__FERNET_KEY: "PLACEHOLDER_AIRFLOW_FERNET_KEY"

  airflow-webserver:
    template: "airflow:{{cookiecutter.airflow_version}}"
    component: "webserver"
    depends_on: ["airflow-init"]
    persistent: true
    health_check: true
    ports: ["webserver:8080"]
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://{{cookiecutter.db_user}}:{{cookiecutter.db_password}}@{{cookiecutter.repo_slug}}_postgres:5432/{{cookiecutter.db_name}}"
      AIRFLOW__CORE__FERNET_KEY: "PLACEHOLDER_AIRFLOW_FERNET_KEY"